# Generated by Django 3.2.7 on 2021-10-08 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0002_auto_20211008_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 35, 15, 489687)),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Regular'), (4, 'Bom'), (5, 'Ótimo')], max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 35, 15, 491063))),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.user')),
            ],
        ),
    ]
