# Generated by Django 3.2.7 on 2021-10-08 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211008_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 41, 5, 52517)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 8, 17, 41, 5, 53014)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.CharField(choices=[('1', 'Péssimo'), ('2', 'Ruim'), ('3', 'Regular'), ('4', 'Bom'), ('5', 'Ótimo')], max_length=50),
        ),
    ]
